### PR TITLE
Fix: Load the category of the workflow step definition.

### LINKED ISSUE #702: [BUG] Can't load the category of the workflow step definition.
**Describe the bug**

Now, Frontend loads the step category from the label `definition.oam.dev/catalog`. But all step definitions define the category by the label `custom.definition.oam.dev/category`. Refer to this [PR change](https://github.com/kubevela/kubevela/commit/4a16b2f6fef159cbbc02e4cd627f8bb3ec37d4e8) It's not matched. 

image

So, we need to change the frontend code. The path is `packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx`

### PR DESCRIPTION
**Pull request by NeerajGartia21**
### Description of your changes

Fixes #702 

Screenshot 2023-03-20 at 3 10 25 PM

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure the frontend changes are ready for review.
- [x] Run `make reviewable`to ensure the server changes are ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

I have added the descriptions to the workflow steps on my own. Please suggest changes to that.

### CODE REVIEW

**Comment by barnettZQG** [comment]
@NeerajGartia21 Thanks for your first PR, please sign the DCO.

**Comment by NeerajGartia21** [comment]
I will sign it off.
Sorry, I didn't notice it.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx [hunk 1]
```diff
@@ -24,44 +24,22 @@ interface DefinitionCatalog {
...
-  'delete-config': 'Config Management',
-  'list-config': 'Config Management',
-  'read-config': 'Config Management',
-  'export-data': 'Config Management',
-  export2config: 'Config Management',
-  export2secret: 'Config Management',
-  suspend: 'Notification',
-};
-
 const defaultCatalog: Record<string, DefinitionCatalog> = {
```
Comment (barnettZQG) [inline packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:27]: Let's change the `catalog` to `category`.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx [hunk 2]
```diff
@@ -24,44 +24,22 @@ interface DefinitionCatalog {
...
+  'Resource Management': {
+    title: 'Resource Management',
+    description: 'Steps for Resource Management',
     definitions: [],
     sort: 2,
   },
-  Approval: {
-    title: 'Approval',
-    description: 'Approval or reject the changes during Workflow or Pipeline progress',
+  'Terraform': {
```
[the remark this answers is not in the document]
Comment (NeerajGartia21) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:40]: steps such as `apply-terraform-config` , `apply-terraform-provider` belongs to this category.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx (hunk 1 above)
Comment (NeerajGartia21) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:27]: sure!
I will replace all the `catalog` with `category`.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx [hunk 3]
```diff
@@ -24,44 +24,22 @@ interface DefinitionCatalog {
...
-  'list-config': 'Config Management',
-  'read-config': 'Config Management',
-  'export-data': 'Config Management',
-  export2config: 'Config Management',
-  export2secret: 'Config Management',
-  suspend: 'Notification',
-};
-
 const defaultCatalog: Record<string, DefinitionCatalog> = {
-  Group: {
```
Comment (barnettZQG) [inline packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:50]: This category is very important, why do we delete it? The `step-group` step type should belong to this category. 

BTW, We can also turn the `step-group` into a stationary button as another solution.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (barnettZQG) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:40]: Oh, maybe we need to change the category for these step definitions.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx (hunk 3 above)
Comment (NeerajGartia21) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:50]: I deleted it because it falls under `Process Control` category , as mentioned [here](https://github.com/kubevela/kubevela/blob/4a16b2f6fef159cbbc02e4cd627f8bb3ec37d4e8/charts/vela-core/templates/defwithtemplate/step-group.yaml#L7).
I should have prioritised it while sorting.

Comment (NeerajGartia21) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:50]: > BTW, We can also turn the `step-group` into a stationary button as another solution.
I think this needs some discussion about where to put the button.

Comment (barnettZQG) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:50]: Oh, let's make `Process Control` the first category.

**Comment by barnettZQG** [comment]
Please rebase the branch from the main.

File: packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx (hunk 3 above)
Comment (NeerajGartia21) [reply packages/velaux-ui/src/components/WorkflowStudio/type-select.tsx:50]: Sure, I'm on it.

**Review by barnettZQG — APPROVED** [review]
lgtm
