### PR TITLE
Fix: Prevent crashes when accessing cluster details

### LINKED ISSUE #685: The page crashes after click an inaccessible cluster
**Describe the bug**
Create an inaccessible cluster. When click the edit button, the entire page crashes and become blank page.

**To Reproduce**
1. Create an inaccessible cluster.
2. Select the current cluster and click the edit button.
3. the entire page crashes and become blank page.

**Expected behavior**
Should prompt for errors to prevent the entire page from crashing into blank page.

**Screenshots**
40b91404a705ccc547929b1e1a4be625
250587ed2b43a308d9e845b35813de9b

**KubeVela Version**

1.6.4

**Additional context**

### PR DESCRIPTION
**Pull request by am6737**
- Added optional chaining to safely access cluster details in `AddClusterDialog`.

This fix addresses the issue where the page crashes when trying to load details for an inaccessible cluster.

### Description of your changes

Fixes #685

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure the frontend changes are ready for review.
- [ ] Run `make reviewable`to ensure the server changes are ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

File: packages/velaux-ui/src/pages/Cluster/components/AddClusterDialog/index.tsx [hunk 1]
```diff
@@ -55,27 +55,28 @@ class AddClusterDialog extends React.Component<Props, State> {
...
-
+  
   onClose = () => {
     this.props.onClose();
     this.resetField();
   };
 
   onOk = () => {
     const { editMode, cluster } = this.state;
+    const { editClusterName } = this.props;
```
Comment (barnettZQG) [inline packages/velaux-ui/src/pages/Cluster/components/AddClusterDialog/index.tsx:66]: What's the need for this code change?

Comment (am6737) [reply packages/velaux-ui/src/pages/Cluster/components/AddClusterDialog/index.tsx:66]: Thank you for pointing this out! I'll go ahead and remove it to clean up the code.

Comment (am6737) [reply packages/velaux-ui/src/pages/Cluster/components/AddClusterDialog/index.tsx:66]: > What's the need for this code change?

Thank you for pointing this out! I'll go ahead and remove it to clean up the code.

**Review by anoop2811 — APPROVED** [review]
LGTM
