### PR TITLE
Fix: Set default values for traits in VelaUX

### LINKED ISSUE #650: [Bug] VelaUX does not set the default value of Trait "cpuscaler"
**Describe the bug**

VelaUX does not set the default value of Trait "cpuscaler"
**To Reproduce**
1. install valaux
2. create one application
3. go to the detail page of this application
4. edit the default Component "webservice"
5. click button "+ " to. add one new trait
6. select "cpuscaler"
7. the Trait Properties are filled by default value
8. click Create button
image

9. check request in Chrome devtool's network tab 
image

10. the value of "cpuscaler" is not set

**Expected behavior**
1. the default value should be set

**Screenshots**

**KubeVela Version**

UI Version: v1.6.4-2f68a03

API Version: v1.6.4-git-1a6b724

**Additional context**

### PR DESCRIPTION
**Pull request by am6737**
- Addressed the issue where default values for traits (including "cpuscaler", "hpa", "resource", "k8s-update-strategy") were not being set properly.

### Description of your changes

Fixes #650

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure the frontend changes are ready for review.
- [ ] Run `make reviewable`to ensure the server changes are ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by wonderflow — APPROVED** [review]

File: packages/velaux-ui/src/components/UISchema/index.tsx [hunk 1]
```diff
@@ -176,6 +177,32 @@ class UISchema extends Component<Props, State> {
     });
   };
 
+  initFormValues = () => {
```
Comment (barnettZQG) [inline packages/velaux-ui/src/components/UISchema/index.tsx:180]: Why do we need to do this?

Comment (am6737) [reply packages/velaux-ui/src/components/UISchema/index.tsx]: Thanks for your feedback! I realized the issue and have updated the code accordingly. 

Looking forward to your thoughts!

**Comment by anoop2811** [comment]
Thank you for your contribution
