### PR TITLE
Fix: Application Graph displays exception stack trace

### LINKED ISSUE #793: [BUG] Application Graph displays exception stack trace
Velaux Application Graph is failed when click to : applications/[APP-NAME]/envbinding/system/status  . An exception stack trace appears.

**To Reproduce**

1. Click an application
2. Click Enviroment
3. Click Status
4. Click Application Graph Tab

**Expected behavior**

Application graph of application

**Screenshots**
image

**KubeVela Version**

1.8.0

**Additional context**

### PR DESCRIPTION
**Pull request by mujinhuakai**
### Description of your changes

Application Graph displays exception stack trace

Fixes #793

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [ ] Run `yarn lint` to ensure the frontend changes are ready for review.
- [ ] Run `make reviewable`to ensure the server changes are ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: packages/velaux-ui/src/components/TreeGraph/component-node.tsx [hunk 1]
```diff
@@ -203,15 +203,15 @@ export const ComponentNode = (props: ComponentNodeProps) => {
 
       <If condition={traits.length > 0}>
         <div className={classNames('label-traits')}>
-          {traits && (
+          {traits && (
```
Comment (barnettZQG) [inline packages/velaux-ui/src/components/TreeGraph/component-node.tsx:206]:
```suggestion
          {traits && traits.length>0 && traits[0]  (                                                                                                                                                                                                                                                                                                                                                                                        
```

File: packages/velaux-ui/src/components/TreeGraph/component-node.tsx [hunk 2]
```diff
@@ -165,7 +165,7 @@ export const ComponentNode = (props: ComponentNodeProps) => {
       </Balloon>
     );
   };
-
+  console.log("--traits--", traits)
```
Comment (barnettZQG) [inline packages/velaux-ui/src/components/TreeGraph/component-node.tsx:168]: Please remove this line.

**Review by barnettZQG — APPROVED** [review]
LGTM
